// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    plans (id) {
        id -> Uuid,
        name -> Varchar,
        price_paise -> Int8,
        currency -> Varchar,
        interval -> Varchar,
        features -> Nullable<Text>,
        active -> Bool,
    }
}

diesel::table! {
    subscriptions (id) {
        id -> Uuid,
        user_id -> Uuid,
        plan_id -> Uuid,
        status -> Varchar,
        razorpay_subscription_id -> Nullable<Varchar>,
        current_period_start -> Nullable<Timestamptz>,
        current_period_end -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    payments (id) {
        id -> Uuid,
        subscription_id -> Uuid,
        user_id -> Uuid,
        amount_paise -> Int8,
        currency -> Varchar,
        status -> Varchar,
        razorpay_payment_id -> Nullable<Varchar>,
        razorpay_order_id -> Nullable<Varchar>,
        paid_at -> Nullable<Timestamptz>,
    }
}

diesel::joinable!(subscriptions -> plans (plan_id));
diesel::joinable!(payments -> subscriptions (subscription_id));

diesel::allow_tables_to_appear_in_same_query!(
    plans,
    subscriptions,
    payments,
);
