// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    users (id) {
        id -> Uuid,
        name -> Varchar,
        email -> Varchar,
        password_hash -> Varchar,
        phone -> Varchar,
        role -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    student_profiles (user_id) {
        user_id -> Uuid,
        grade -> Int2,
        mother_tongue -> Varchar,
        state_of_residence -> Varchar,
        board -> Nullable<Varchar>,
        school_id -> Nullable<Uuid>,
        parent_email -> Nullable<Varchar>,
    }
}

diesel::table! {
    teacher_profiles (user_id) {
        user_id -> Uuid,
        languages -> Array<Varchar>,
        qualifications -> Text,
        bio -> Nullable<Text>,
        verified -> Bool,
        rating -> Nullable<Float8>,
    }
}

diesel::joinable!(student_profiles -> users (user_id));
diesel::joinable!(teacher_profiles -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    student_profiles,
    teacher_profiles,
);
