// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    languages (id) {
        id -> Uuid,
        name -> Varchar,
        script -> Varchar,
        iso_code -> Varchar,
        family -> Varchar,
    }
}

diesel::table! {
    curricula (id) {
        id -> Uuid,
        language_id -> Uuid,
        grade -> Int2,
        title -> Varchar,
        description -> Nullable<Text>,
    }
}

diesel::table! {
    modules (id) {
        id -> Uuid,
        curriculum_id -> Uuid,
        title -> Varchar,
        description -> Text,
        skill_type -> Varchar,
        order_index -> Int4,
        estimated_minutes -> Int4,
    }
}

diesel::table! {
    lessons (id) {
        id -> Uuid,
        module_id -> Uuid,
        title -> Varchar,
        description -> Text,
        lesson_type -> Varchar,
        content -> Text,
        media_urls -> Array<Varchar>,
        duration_minutes -> Int4,
        order_index -> Int4,
    }
}

diesel::table! {
    enrollments (id) {
        id -> Uuid,
        student_id -> Uuid,
        language_id -> Uuid,
        grade -> Int2,
        proficiency -> Varchar,
        enrolled_at -> Timestamptz,
    }
}

diesel::table! {
    progress (id) {
        id -> Uuid,
        student_id -> Uuid,
        lesson_id -> Uuid,
        completed_at -> Timestamptz,
        score -> Nullable<Float8>,
        time_spent_seconds -> Int4,
    }
}

diesel::joinable!(curricula -> languages (language_id));
diesel::joinable!(modules -> curricula (curriculum_id));
diesel::joinable!(lessons -> modules (module_id));
diesel::joinable!(enrollments -> languages (language_id));
diesel::joinable!(progress -> lessons (lesson_id));

diesel::allow_tables_to_appear_in_same_query!(
    languages,
    curricula,
    modules,
    lessons,
    enrollments,
    progress,
);
