// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    content_items (id) {
        id -> Uuid,
        language_id -> Uuid,
        module_id -> Uuid,
        lesson_id -> Nullable<Uuid>,
        content_type -> Varchar,
        title -> Varchar,
        body -> Text,
        media_urls -> Nullable<Array<Varchar>>,
        status -> Varchar,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    media_assets (id) {
        id -> Uuid,
        filename -> Varchar,
        content_type -> Varchar,
        url -> Varchar,
        size_bytes -> Int8,
        uploaded_by -> Uuid,
        uploaded_at -> Timestamptz,
    }
}

diesel::table! {
    content_reviews (id) {
        id -> Uuid,
        content_item_id -> Uuid,
        reviewer_id -> Uuid,
        status -> Varchar,
        comments -> Nullable<Text>,
        reviewed_at -> Timestamptz,
    }
}

diesel::joinable!(content_reviews -> content_items (content_item_id));

diesel::allow_tables_to_appear_in_same_query!(
    content_items,
    media_assets,
    content_reviews,
);
