// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    live_classes (id) {
        id -> Uuid,
        teacher_id -> Uuid,
        language_id -> Uuid,
        title -> Varchar,
        description -> Nullable<Text>,
        scheduled_at -> Timestamptz,
        duration_minutes -> Int4,
        max_students -> Int4,
        status -> Varchar,
        meeting_url -> Nullable<Varchar>,
    }
}

diesel::table! {
    class_enrollments (id) {
        id -> Uuid,
        class_id -> Uuid,
        student_id -> Uuid,
        enrolled_at -> Timestamptz,
        attended -> Bool,
    }
}

diesel::table! {
    teacher_availability (id) {
        id -> Uuid,
        teacher_id -> Uuid,
        day_of_week -> Int4,
        start_time -> Varchar,
        end_time -> Varchar,
    }
}

diesel::joinable!(class_enrollments -> live_classes (class_id));

diesel::allow_tables_to_appear_in_same_query!(
    live_classes,
    class_enrollments,
    teacher_availability,
);
