// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    notifications (id) {
        id -> Uuid,
        user_id -> Uuid,
        notification_type -> Varchar,
        channel -> Varchar,
        title -> Varchar,
        body -> Text,
        status -> Varchar,
        sent_at -> Nullable<Timestamptz>,
        read_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    notification_preferences (user_id) {
        user_id -> Uuid,
        email_enabled -> Bool,
        sms_enabled -> Bool,
        push_enabled -> Bool,
        digest_frequency -> Nullable<Varchar>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    notifications,
    notification_preferences,
);
