// This file will be auto-generated by `diesel print-schema`.
// For now, we define it manually to match our migration.

diesel::table! {
    assessments (id) {
        id -> Uuid,
        student_id -> Uuid,
        module_id -> Uuid,
        assessment_type -> Varchar,
        status -> Varchar,
        started_at -> Timestamptz,
        submitted_at -> Nullable<Timestamptz>,
        time_limit_minutes -> Nullable<Int4>,
    }
}

diesel::table! {
    questions (id) {
        id -> Uuid,
        assessment_id -> Uuid,
        question_text -> Text,
        question_type -> Varchar,
        options -> Nullable<Text>,
        media_url -> Nullable<Varchar>,
        max_score -> Int4,
        correct_answer -> Text,
        order_index -> Int4,
    }
}

diesel::table! {
    student_answers (id) {
        id -> Uuid,
        assessment_id -> Uuid,
        question_id -> Uuid,
        answer -> Text,
        score -> Nullable<Int4>,
        is_correct -> Nullable<Bool>,
    }
}

diesel::table! {
    credits (id) {
        id -> Uuid,
        student_id -> Uuid,
        language_id -> Uuid,
        grade -> Int4,
        semester -> Int4,
        score -> Float8,
        grade_letter -> Varchar,
        credit_points -> Float8,
        status -> Varchar,
        certificate_url -> Nullable<Varchar>,
        verification_code -> Varchar,
        issued_at -> Timestamptz,
    }
}

diesel::joinable!(questions -> assessments (assessment_id));
diesel::joinable!(student_answers -> assessments (assessment_id));
diesel::joinable!(student_answers -> questions (question_id));

diesel::allow_tables_to_appear_in_same_query!(
    assessments,
    questions,
    student_answers,
    credits,
);
